CREATE TABLE if not exists departamento (
                                            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                                            identificador UUID UNIQUE NOT NULL,
                                            nome VARCHAR(255) UNIQUE NOT NULL
);

INSERT INTO public.departamento (identificador, nome, deletado)
VALUES
    (gen_random_uuid(), 'COMERCIAL', false),
    (gen_random_uuid(), 'DESENVOLVIMENTO', false),
    (gen_random_uuid(), 'FINANCEIRO', false)
ON CONFLICT (nome) DO NOTHING;
